### ISSUE TITLE
Window height grows continuously on iPad Safari

### ISSUE THREAD

**Issue by charuwts** [KumarAbhirup/circle_crush#1]
When the game starts the game container grows vertically without stopping. I'd provide a screenshot but it doesn't really show what's happening.

**Comment by kumarabhirup** [comment]
Bug spotted on a iOS device. Didn't really figure out why I don't see the bug on Android.
Will roll a bug fix soon. Stay tuned!

**Comment by kumarabhirup** [comment]
Circle Crush game updates

Name changed to Star Crush
The plain circles are now Yellow and Grey stars
The white neutral circle is now a Grenade
The rotating wheels are now lowered a bit for easier gameplay.

The "Start button fall down the screen" bug is not yet confirmed if fixed or not. It should be fixed by now. If not, let me know.

Play it here :rocket: https://withkoji.com/~kumar_abhirup/circle-crush-

**Comment by kumarabhirup** [comment]
Issue is now fixed 🚀 Tried and Tested on iOS. Thanks for opening this issue.
